### ISSUE TITLE
[FEATURE] Build targets do not consider ARM based architectures

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-sdk-for-sap-odata#6]
### Is your feature request related to a problem? Please describe.

The build targets defined in [build.targets](https://github.com/Azure/azure-sdk-for-sap-odata/blob/main/build.targets) do not consider ARM-based architectures. This especially excludes user of Apple Silicon (M1, M2 based machines).

### Describe the solution you'd like

Enhance the build matrix to consider ARM64-based systems

### Describe alternatives you've considered

I do not see any alternative paths.

### Additional context

n.a.

**Comment by WillEastbury** [comment]
This is simply adding the line for the supported net60 target to the targets file. This should be easy enough. I'm sure it was there before so not entirely sure where it's gone.

**Comment by WillEastbury** [comment]
The supported .net RIDs to add to the target file can be found here. Note that this will extend the build time for each added target. 
https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#using-rids

**Comment by WillEastbury** [comment]
The idea is that the publishtobinaries.cmd file will build all of the targets in the build file and we check them in so there will be a prebuilt ARM binary in the zip file. 😊

Thanks,
Will Eastbury
Principal FastTrack Engineering Manager (He, Him, His) | FastTrack for Azure | Azure Engineering
Sent from Outlook<http://aka.ms/weboutlook>

**Comment by felihong** [comment]
Update with pull request #29

**Comment by lechnerc77** [comment]
I assume osx.13-arm64 is the right choice as I would target Mac/MacBooks and not iOS devices (although iPad Pro might be used, but more an edge case imho)

**Comment by WillEastbury** [comment]
Why not add both? It's only a build target - we can generate both for a single change.
